version: '3'

services:

  php:
    container_name: crawler-php
    working_dir: /var/www/html
    build: ./php5.6
    restart: ${RESTART_POLICY}
    ports:
      - "${PHP_LOCAL_PORT}:80"
    volumes:
      - ${PROJECTS_PATH}:/var/www/html
    links:
      - mysql
    networks:
        - crawler-network

  mysql:
    container_name: crawler-mysql
    build: ./mysql5.7
    restart: ${RESTART_POLICY}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${DEFAULT_DATABASE}
      - MYSQL_USER=${DEFAULT_USER}
      - MYSQL_PASSWORD=${DEFAULT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DEFAULT_ROOT_PASSWORD}
    networks:
      - crawler-network

networks:
  crawler-network:
    driver: bridge